Repository fga-eps-mds/2021.2-Noctua, pull requests merged in 2022-04, with the labels that each got.

#100 Hotfix#81/correcao docker
  README.md
  docker-compose.dev.yml
  front/Dockerfile.dev
Labels: bug, documentation, Dev

#104 Feature#103/models salario magistrados
  server/src/models/SalarioMagistrados.ts
Labels: enhancement, Time A, Dev, Feature

#105 Feat#95/requisicoes backend
  server/package.json
  server/src/config/database.ts
  server/src/controller/CotaParlamentarController.ts
  server/src/models/CotaParlamentar.ts
  server/src/routes/routes.ts
  server/src/server.ts
  server/tsconfig.json
  server/yarn.lock
Labels: Time B, Dev

#112 Documentation#88/documentos sprint 8
  docs/Sprints/Sprint Planning - 8.md
  docs/Sprints/SprintsReviews/Sprint review - 8.md
Labels: documentation, Time B, SM

#109 Feat#106 Criado requisições para buscar dados no banco
  server/src/controller/SalarioDosMagistradosController.ts
Labels: Time A, Dev, Feature

#120 Feat#91/testes automatizados
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/pagina_inicial.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: Time A, SM, DevOps, PO, Feature

#111 docs(#87): documentaçao sprint 7
  docs/Sprints/Sprint Planning - 7.md
  docs/Sprints/SprintsReviews/Sprint review - 6.md
  docs/Sprints/SprintsReviews/Sprint review - 7.md
Labels: documentation, Time B, SM

#121 Documentation#116/documentos sprint 10
  docs/Sprints/Sprint Planning - 10.md
  docs/Sprints/SprintsReviews/Sprint review - 10.md
Labels: documentation, Time B

#113 Documentation#98/documentos sprint 9
  docs/Sprints/Sprint Planning - 9.md
  docs/Sprints/SprintsReviews/Sprint review - 9.md
Labels: documentation, Time B, SM

#124 feat(#123):Configuração metabase-docker
  docker-compose.dev.yml
Labels: Time B, DevOps

#125 feat(#90)Criação da página Salário dos Magistrados
  front/src/Router.tsx
  front/src/components/Navbar.tsx
  front/src/pages/timeA/PowerBiReport.tsx
  front/src/pages/timeA/SalarioMagistrados.tsx
  front/src/pages/timeA/css/PowerBI.css
Labels: Time A, SM, DevOps, PO, Feature

#119 Feature#118/remocao das credenciais
  server/.env
  server/package.json
  server/src/controller/EmailController.ts
  server/yarn.lock
Labels: Dev

#134 Feat#133/popular banco
  server/src/controller/SalarioDosMagistradosController.ts
  server/src/models/SalarioDosMagistrados.ts
  server/src/routes/routes.ts
Labels: Time A, Dev, Feature

#137 Feat#96/implementacao metabase
  front/package.json
  front/src/pages/timeB/GastosDeputados.tsx
  front/src/pages/timeB/MetabaseReport.tsx
  front/src/pages/timeB/PowerBiReport.tsx
  front/src/pages/timeB/css/Metabase.css
Labels: Time B, DevOps

#139 Alterando o arquivo da models como correção
  server/src/models/SalarioDosMagistrados.ts
Labels: bug, Time A, Dev, Feature

#150 Implementado dashboard e seus respectivos filtros
  front/src/pages/timeA/MetabaseSalario.tsx
  front/src/pages/timeA/PowerBiReport.tsx
  front/src/pages/timeA/SalarioMagistrados.tsx
  front/src/pages/timeA/css/Metabase.css
Labels: Time A, Dev, Feature

#146 Docs#142/sprint 11
  docs/Sprints/Sprint Planning - 11.md
  docs/Sprints/SprintsReviews/Sprint review - 11.md
Labels: documentation, Time B, SM

#147 Documentation#144/sprint 12
  docs/Sprints/Sprint Planning - 12.md
  docs/Sprints/SprintsReviews/Sprint review - 12.md
Labels: documentation, Time B, SM

#151 Documentation#149/mudanca de titulos sprints
  docs/Sprints/Sprint Planning - 0 - Time B.md
  docs/Sprints/Sprint Planning - 1 - Time B.md
  docs/Sprints/Sprint Planning - 10 - Time B.md
  docs/Sprints/Sprint Planning - 2 - Time B.md
  docs/Sprints/Sprint Planning - 3 - Time B.md
  docs/Sprints/Sprint Planning - 4 - Time B.md
  docs/Sprints/Sprint Planning - 5 - Time B.md
  docs/Sprints/Sprint Planning - 6 - Time B.md
  docs/Sprints/Sprint Planning - 7 - Time B.md
  docs/Sprints/Sprint Planning - 8 - Time B.md
  docs/Sprints/Sprint Planning - 9 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 0 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 1 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 10 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 2 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 3 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 4 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 5 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 6 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 7 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 8 - Time B.md
  docs/Sprints/SprintsReviews/Sprint review - 9 - Time B.md
Labels: documentation, Time B, SM

#152 Docs#97/revisao docs
  docs/Documento_de_Arquitetura.md
  docs/Documento_de_Visão.md
  docs/Estrutura_Analítica_do_Projeto.md
  docs/Manual de Identidade Visual.md
  docs/Metodologia.md
  docs/Termo_de_Abertura_de_Projeto.md
  docs/img/visao_logica.png
  front/=1.0.0
  front/=7.21.4
  front/package.json
Labels: documentation, Time B, Time A

#157 Documentation#138/post mortem
  docs/Post Mortem.md
Labels: documentation, Time B
