Repository fga-eps-mds/2021.2-Noctua, pull requests merged in 2022-03, with the labels that each got.

#48 Feature#45/config ambiente
  docker-compose.yml
  front/Dockerfile
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.css
  front/src/App.tsx
  front/src/index.css
  front/src/index.tsx
  front/src/logo.svg
  front/src/react-app-env.d.ts
  front/tsconfig.json
  front/yarn.lock
  server/Dockerfile
  server/package.json
  server/src/config/database.ts
  server/src/routes/routes.ts
  server/src/server.ts
  server/tsconfig.json
  server/yarn.lock
Labels: Arquiteto, DevOps

#52 Feature#49/home page
  .gitignore
  front/package.json
  front/public/favicon.ico
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.tsx
  front/src/Router.tsx
  front/src/components/Card.tsx
  front/src/components/Footer.tsx
  front/src/components/Navbar.tsx
  front/src/index.tsx
  front/src/logo.svg
  front/src/pages/Home.tsx
  front/src/pages/timeB/GastosDeputados.tsx
  front/yarn.lock
Labels: Time B, Dev, Feature

#46 Adicionando roadmap
  docs/ROADMAP-convertido.pdf
  docs/ROADMAP.png
Labels: documentation

#63 Feature(#50)/power bi
  front/package.json
  front/src/Router.tsx
  front/src/components/Footer.tsx
  front/src/components/FormFaleConosco.tsx
  front/src/components/Navbar.tsx
  front/src/pages/shared/FaleConosco.tsx
  front/src/pages/shared/Home.tsx
  front/src/pages/timeB/GastosDeputados.tsx
  front/src/pages/timeB/PowerBiReport.tsx
  front/src/pages/timeB/css/PowerBI.css
  front/yarn.lock
Labels: Time B, Dev

#64 Feature#54/perguntas frequentes
  front/src/Router.tsx
  front/src/components/Navbar.tsx
  front/src/pages/shared/PerguntasFrequentes.tsx
Labels: Time B, Dev, Feature

#65 Feature(#51)/fale conosco
  front/package.json
  front/src/components/Footer.tsx
  front/src/components/FormFaleConosco.tsx
  front/src/components/Navbar.tsx
  front/src/pages/shared/FaleConosco.tsx
  front/src/pages/shared/Home.tsx
  front/src/services/api.ts
  front/yarn.lock
  server/package.json
  server/src/controller/EmailController.ts
  server/src/models/Email.ts
  server/src/routes/routes.ts
  server/yarn.lock
Labels: Time B, Dev, Feature

#76 Adicionando template de issue
  docs/Políticas/template_issue.md
Labels: documentation

#78 Adicionando template de pull request
  docs/Políticas/template_pull_request.md
Labels: documentation, Dev

#93 Alterando o dataset.
  front/src/pages/shared/Home.tsx
Labels: enhancement, Time A, Dev
